### ISSUE TITLE
Soporte para Visual Studio

### ISSUE THREAD

**Issue by GiovanniSCESP** [Erawaa/MessiScriptInterpreter#3]
Buenas, el proyecto de un lenguaje de messi me hizo bastante gracia por lo que lo usé como base para empezar a hacer una extensión para visual studio que de soporte a este lenguaje, soy nuevo haciendo extensiones en visual studio por lo que aún desconozco muchas cosas. Tengo el proyecto público en el perfil.

**Comment by Erawaa** [comment]
Buenas, Giovanni! Que buena onda! Ahí estuve viendo el repo y el ejemplo se ve super copado. Y me alegra que te esté sirviendo de base para aprender sobre extensiones. Dejame un comentario en este issue si lo llegás a agregar al marketplace de extensiones de VSCode, así lo puedo compartir en el este repo. Saludos!

**Comment by GiovanniSCESP** [comment]
Ya está publicado en el marketplace https://marketplace.visualstudio.com/items?itemName=GiovanniSCESP.messiscript-syntax quizás en un futuro haga algún blog con tutoriales con el tema porque veo que falta muchos ejemplos y documentación para principiantes sobre todo en español y sobre extensiones para lenguajes.

**Comment by Erawaa** [comment]
Te quedó buenísimo! Ahí mencioné la extensión en el README del proyecto y dejé un link a tu perfil. Gracias!
Éxitos si decidís empezar ese blog en algún momento. Estaría bueno que circulen más tutoriales en español. En especial para cosas tan específicas.
