### ISSUE TITLE
Mejora de diccionario <3

### ISSUE THREAD

**Issue by leantorres73** [Erawaa/MessiScriptInterpreter#4]
"fútbol": Cambia el signo de la posición actual de la lista.

La palabra "fulbo" deberia hacer lo mismo. Probablemente la palabra mas usada por nuestro queridisimo Lionel Andrés Messi Cuccittini.

Saludos hermoso lenguaje

**Comment by Erawaa** [comment]
Que tal! Concuerdo totalmente, jajajajaja. Pero preferiría mantener las bases del lenguaje lo más fijas posible. No me quiero ver tentado a empezar a agregarle muchas cosas.

Saludos y gracias por la buena onda!
