### ISSUE TITLE
Tamaño máximo de la lista

### ISSUE THREAD

**Issue by jorgemo-fever** [Erawaa/MessiScriptInterpreter#5]
No veo en [README.md](https://github.com/Erawaa/MessiScriptInterpreter/blob/bf1339551cafcdc6609ec749fa4de5d8e909f278/README.md) el tamaño de la lista, ni operaciones para determinarlo. Creo que esto es esencial para entender el lenguaje.

Entiendo, por tanto, que la lista es dinámica y de tamaño flexible?

**Comment by Erawaa** [comment]
Hola, Jorge! Aprecio el interés en el lenguaje! La lista no tiene un tamaño definido por diseño porque no me pareció relevante. Si se usaran solo 10000 posiciones o 100, la forma en la que el lenguaje funciona no se vería afectada. Con lo cual prefiero que eso quede determinado por la implementación.

Mi implementación (el interprete que está en este repositorio) está escrita en Python, y para la lista se usó, justamente, el tipo de dato lista que viene con el lenguaje. Empieza con solo un 0 como primer elemento. A medida que uno se mueve hacia la derecha, se adjuntan nuevos elementos también seteados en 0. Con lo cual hacés bien en asumir, en este caso, que la lista es dinámica.

Saludos! :hugs:
