### ISSUE TITLE
English please

### ISSUE THREAD

**Issue by vutran1710** [Erawaa/MessiScriptInterpreter#8]
I'd love to know what this is about lol

**Comment by Erawaa** [comment]
Hi! I am glad you are interested in the project. MessiScript is an esoteric language in which every piece of code is read as if it was a narrated play by Lionel Messi. It works very similarly to Brainfuck, and it takes a bit from the Shakespeare Programming Language. The commands and the words are in Spanish though, so it is difficult to appreciate the joke if you don't know the language.

If you are interested in knowing more about it, let me know and I can give you a more detailed explanation on how it works.

Have a good one!
